### ISSUE TITLE
Menu items not matching with their sections

### ISSUE THREAD

**Issue by Rantelo** [Intelimetrica/wizardo#20]
In the section **Create a generator**, the documentation has 3 subsections
- Setup
- Create command
- List command

They are not matching with the titles in the SidebarMenu.

![image](https://user-images.githubusercontent.com/5539993/51413356-4f0cd080-1b34-11e9-8586-2427aef01ca5.png)

-----
We need to fix this mismatch in the sidebar.

**Comment by Saitama2016** [comment]
Made changes to the Side Navigation Bar [here](https://github.com/Intelimetrica/wizardo/pull/21).

**Comment by Rantelo** [comment]
This issue was solved by RP #21
