### ISSUE TITLE
Create collapsable navbar.

### ISSUE THREAD

**Issue by Rantelo** [Intelimetrica/wizardo#5]
Navbar displays well in computer sized screens, but not in mobile.
We could collapse the navbar to the left for smaller screens and add a toggle button.
![whatsapp image 2018-11-27 at 10 51 59](https://user-images.githubusercontent.com/5539993/49097553-982a5d80-f232-11e8-8f72-453ac9e54e90.jpeg)

**Comment by AhmedElbohoty** [comment]
I am working on it now.

**Comment by iburgos72** [comment]
Solved in #14
